### PR TITLE
Fix/style/layout responsiveness/set up

### LINKED ISSUE #103: Make layout fit to all screen sizes - set up
### **Description:**
This is a subtask from #82. This tasks sets up padding dimensions and typography to ensure responsive design across all screens, enhancing user experience and visual consistency.

### **Steps:**
- [x] Read [App Style Guide](https://github.com/PeriodPals/periodpals/wiki/App-Style-Guide#app-style-guide).
- [x] Define padding for UI components.
- [x] Configure typography settings for readability.

### **Tests:**
Can't test. This is like for the colour theme.

### PR DESCRIPTION
**Pull request by francelu**
# Setup Padding Dimensions and Typography for Responsive Design (#82 Subtask)

## Description
This PR closes #103 and establishes standardized padding and typography to ensure a responsive design and visual consistency across all screens, in alignment with the App Style Guide. It introduces utility files for padding and custom fonts, supporting subtask #82 and enhancing overall readability and user experience.

## Changes
- Implemented standardized padding dimensions for UI components.
- Configured typography settings to enhance readability and maintain alignment with the App Style Guide.
- **Screens have not been modified yet.** This will be addressed in subsequent subtasks of #82.

#### Added
- `app/src/main/java/com/android/periodpals/ui/theme/`:
  - `Dimens.kt`: Defines padding values.
  - `AppUtil.kt`: Provides app-specific dimensions.

- `app/src/main/res/font/`: Various Nunito Sans font files (may not all be used in the final application):
  - `nunito_sans_black.ttf`
  - `nunito_sans_black_italic.ttf`
  - `nunito_sans_bold.ttf`
  - `nunito_sans_bold_italic.ttf`
  - `nunito_sans_extra_bold.ttf`
  - `nunito_sans_extra_bold_italic.ttf`
  - `nunito_sans_extra_light.ttf`
  - `nunito_sans_extra_light_italic.ttf`
  - `nunito_sans_italic.ttf`
  - `nunito_sans_light.ttf`
  - `nunito_sans_light_italic.ttf`
  - `nunito_sans_regular.ttf`
  - `nunito_sans_semi_bold.ttf`
  - `nunito_sans_semi_bold_italic.ttf`

#### Modified
- `Type.kt`: Adjusted font and size configurations.
- `Theme.kt`: Updated to set the appropriate font and typography based on screen size.
- `MapScreenTest.kt`: Removed `PeriodPalsAppTheme` wrapping; now directly sets content to `MapScreen`.

## Dependency Updates
- Added `androidx.compose.material3:material3-window-size-class:1.3.0` to facilitate window size class support. 

## Testing
- Direct testing is not applicable, as this setup mirrors our color theme configuration.
- Visual inspection is required to verify padding and typography consistency across the app on each screen, to be followed up in #82 and its subtasks.

## Reviewer Notes
If you encounter any parts of the code that are unclear or feel that documentation is lacking, please do not hesitate to point it out. Your feedback is essential to improve the overall quality and maintainability of the code.

## Resources
- Tutorial [video](https://www.youtube.com/watch?v=Dj_X-RKL-c0)
- Font download [page](https://www.1001fonts.com/nunito-sans-font.html)

### CODE REVIEW

File: app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt
Comment (Harrish92) [inline app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt:1]: Could you please write comments to clarify what exactly ProvideAppUtils does?

**Review by Harrish92 — CHANGES_REQUESTED** [review]
## Summary
Comments for the `ProvideAppUtils` class are needed to improve code readability and maintainability. Otherwise, good job on standardizing padding and typography. 
## Documentation
- Ensure that the comments are clear and provide sufficient information for future developers to understand the code.

## Steps before PR approved
- Add detailed comments to the `ProvideAppUtils` class to improve code readability and maintainability.

**Review by Harrish92 — APPROVED** [review]
LGTM

File: app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt
Comment (francelu) [reply app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt:1]: Added.

File: app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt [hunk 1]
```diff
@@ -0,0 +1,75 @@
+package com.android.periodpals.ui.theme
+
+import androidx.compose.ui.unit.Dp
+import androidx.compose.ui.unit.dp
+
+data class Dimens(
```
Comment (lazarinibruno) [inline app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt:6]: Question: I'm curious, where do all of these values come from?

File: app/src/main/java/com/android/periodpals/ui/theme/Theme.kt [hunk 2]
```diff
@@ -134,5 +143,47 @@ fun PeriodPalsAppTheme(
...
+    }
+    WindowWidthSizeClass.Expanded -> {
+      appDimens = ExpandedDimens
+      typography = ExpandedTypography
+      dims = "ExpandedDimens"
+    }
+  }
+
+  // TODO delete
+  Toast.makeText(LocalContext.current, dims, Toast.LENGTH_SHORT).show()
```
Comment (lazarinibruno) [inline app/src/main/java/com/android/periodpals/ui/theme/Theme.kt:181]: Since it is marked as to be deleted, why is it still there?

**Review by lazarinibruno — CHANGES_REQUESTED** [review]
## Summary

Thanks for the hard work :DD

- The addition of `Dimens.kt`, `Type.kt` and `Theme.kt` help will help have an app that looks good and is consistent.
  

## Improvements

- Could you add a short documentation above the `Dimens` data class that explains what it is?
  

## Questions

- There are many seemingly aribitrary values. For instance, the `Dimens` data class; or in `Theme.kt` there is the following line of code `if (config.screenWidthDp <= 360)`. I just wonder where does all of these values come from.
  

## Steps before merge

- Add the KDoc comment above the `Dimens` data class.

File: app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt (hunk 1 above)
Comment (francelu) [reply app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt:6]: This is an initial setup for screen responsiveness. I'll adapt and fine-tune the paddings as I integrate them into the screens. Depending on the specific requirements, some paddings may need to be added or removed.

The main approach involves retrieving the screen size and applying a suitable padding set based on the device's width. This helps categorize devices into compact (S, M, L), medium, or extended, adjusting both padding and typography sizes to fit different screens effectively.

An alternative, though more precise, method would calculate proportional padding for each component (e.g., 24dp out of 418dp equals xx% of width). This would involve applying padding as a percentage of the display's width. However, it sacrifices readability and makes typography sizing harder to adapt and maintain.

File: app/src/main/java/com/android/periodpals/ui/theme/Theme.kt (hunk 2 above)
Comment (francelu) [reply app/src/main/java/com/android/periodpals/ui/theme/Theme.kt:181]: My bad, I forgot. I just used it to know what kind of device I was running xD

**Comment by francelu** [comment]
@lazarinibruno  
Regarding your question about the seemingly arbitrary values, I'd watched a [video](https://www.youtube.com/watch?v=Dj_X-RKL-c0) where these values were used. If you'd prefer, I can adjust them or convert them into vals for better clarity and consistency. Let me know your thoughts!

File: app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt (hunk 1 above)
Comment (lazarinibruno) [reply app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt:13]: Perfect! Thanks for clarifying:)

**Comment by lazarinibruno** [comment]
> @lazarinibruno  
> Regarding your question about the seemingly arbitrary values, I'd watched a [video](https://www.youtube.com/watch?v=Dj_X-RKL-c0) where these values were used. If you'd prefer, I can adjust them or convert them into vals for better clarity and consistency. Let me know your thoughts!

It's perfect the way it is, I just wanted to understand!

**Review by lazarinibruno — APPROVED** [review]

File: app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt (hunk 1 above)
Comment (francelu) [reply app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt:13]: You're welcome !
